language: go
sudo: false

go_import_path: github.com/uudashr/gopkgs/v2

go:
  - 1.14.x
  - 1.13.x
  - 1.12.x
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - 1.8.x
  - tip

matrix:
  allow_failures:
    - go: tip

os:
  - linux
  - osx

install:
  - env GO111MODULE=on go mod download || go get -u

before_script:
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.8 ]]; then echo 'Skipping golangci-lint install'; else make lint-prepare; fi

script:
  - if [[ "$TRAVIS_GO_VERSION" =~ ^1\.8 ]]; then echo 'Skipping golangci-lint run'; else env GO111MODULE=on make lint; fi
  - env GO111MODULE=on make test
